//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class Detection3DArrayMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/Detection3DArray";
        public override string RosMessageName => k_RosMessageName;

        //  A list of 3D detections, for a multi-object 3D detector.
        public Std.HeaderMsg header;
        //  A list of the detected proposals. A multi-proposal detector might generate
        //    this list with many candidate detections generated from a single input.
        public Detection3DMsg[] detections;

        public Detection3DArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.detections = new Detection3DMsg[0];
        }

        public Detection3DArrayMsg(Std.HeaderMsg header, Detection3DMsg[] detections)
        {
            this.header = header;
            this.detections = detections;
        }

        public static Detection3DArrayMsg Deserialize(MessageDeserializer deserializer) => new Detection3DArrayMsg(deserializer);

        private Detection3DArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.detections, Detection3DMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.detections);
            serializer.Write(this.detections);
        }

        public override string ToString()
        {
            return "Detection3DArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\ndetections: " + System.String.Join(", ", detections.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
