//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class Detection3DMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/Detection3D";
        public override string RosMessageName => k_RosMessageName;

        //  Defines a 3D detection result.
        // 
        //  This extends a basic 3D classification by including the pose of the
        //  detected object.
        public Std.HeaderMsg header;
        //  Class probabilities. Does not have to include hypotheses for all possible
        //    object ids, the scores for any ids not listed are assumed to be 0.
        public ObjectHypothesisWithPoseMsg[] results;
        //  3D bounding box surrounding the object.
        public BoundingBox3DMsg bbox;
        //  ID used for consistency across multiple detection messages. Detections
        //  of the same object in different detection messages should have the same id.
        //  This field may be empty.
        public string id;
        //  Source data that generated this classification are not a part of the message.
        //  If you need to access them, use an exact or approximate time synchronizer in
        //  your code, as this message's header should match the header of the source
        //  data.

        public Detection3DMsg()
        {
            this.header = new Std.HeaderMsg();
            this.results = new ObjectHypothesisWithPoseMsg[0];
            this.bbox = new BoundingBox3DMsg();
            this.id = "";
        }

        public Detection3DMsg(Std.HeaderMsg header, ObjectHypothesisWithPoseMsg[] results, BoundingBox3DMsg bbox, string id)
        {
            this.header = header;
            this.results = results;
            this.bbox = bbox;
            this.id = id;
        }

        public static Detection3DMsg Deserialize(MessageDeserializer deserializer) => new Detection3DMsg(deserializer);

        private Detection3DMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.results, ObjectHypothesisWithPoseMsg.Deserialize, deserializer.ReadLength());
            this.bbox = BoundingBox3DMsg.Deserialize(deserializer);
            deserializer.Read(out this.id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.results);
            serializer.Write(this.results);
            serializer.Write(this.bbox);
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "Detection3DMsg: " +
            "\nheader: " + header.ToString() +
            "\nresults: " + System.String.Join(", ", results.ToList()) +
            "\nbbox: " + bbox.ToString() +
            "\nid: " + id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
