//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class Detection3DMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/Detection3D";
        public override string RosMessageName => k_RosMessageName;

        //  Defines a 3D detection result.
        // 
        //  This extends a basic 3D classification by including position information,
        //    allowing a classification result for a specific position in an image to
        //    to be located in the larger image.
        public Std.HeaderMsg header;
        //  Class probabilities. Does not have to include hypotheses for all possible
        //    object ids, the scores for any ids not listed are assumed to be 0.
        public ObjectHypothesisWithPoseMsg[] results;
        //  3D bounding box surrounding the object.
        public BoundingBox3DMsg bbox;
        //  The 3D data that generated these results (i.e. region proposal cropped out of
        //    the image). This information is not required for all detectors, so it may
        //    be empty.
        public Sensor.PointCloud2Msg source_cloud;
        //  If this message was tracking result, this field set true.
        public bool is_tracking;
        //  ID used for consistency across multiple detection messages. This value will
        //    likely differ from the id field set in each individual ObjectHypothesis.
        //  If you set this field, be sure to also set is_tracking to True.
        public string tracking_id;

        public Detection3DMsg()
        {
            this.header = new Std.HeaderMsg();
            this.results = new ObjectHypothesisWithPoseMsg[0];
            this.bbox = new BoundingBox3DMsg();
            this.source_cloud = new Sensor.PointCloud2Msg();
            this.is_tracking = false;
            this.tracking_id = "";
        }

        public Detection3DMsg(Std.HeaderMsg header, ObjectHypothesisWithPoseMsg[] results, BoundingBox3DMsg bbox, Sensor.PointCloud2Msg source_cloud, bool is_tracking, string tracking_id)
        {
            this.header = header;
            this.results = results;
            this.bbox = bbox;
            this.source_cloud = source_cloud;
            this.is_tracking = is_tracking;
            this.tracking_id = tracking_id;
        }

        public static Detection3DMsg Deserialize(MessageDeserializer deserializer) => new Detection3DMsg(deserializer);

        private Detection3DMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.results, ObjectHypothesisWithPoseMsg.Deserialize, deserializer.ReadLength());
            this.bbox = BoundingBox3DMsg.Deserialize(deserializer);
            this.source_cloud = Sensor.PointCloud2Msg.Deserialize(deserializer);
            deserializer.Read(out this.is_tracking);
            deserializer.Read(out this.tracking_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.results);
            serializer.Write(this.results);
            serializer.Write(this.bbox);
            serializer.Write(this.source_cloud);
            serializer.Write(this.is_tracking);
            serializer.Write(this.tracking_id);
        }

        public override string ToString()
        {
            return "Detection3DMsg: " +
            "\nheader: " + header.ToString() +
            "\nresults: " + System.String.Join(", ", results.ToList()) +
            "\nbbox: " + bbox.ToString() +
            "\nsource_cloud: " + source_cloud.ToString() +
            "\nis_tracking: " + is_tracking.ToString() +
            "\ntracking_id: " + tracking_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
