//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DangerZone
{
    [Serializable]
    public class SnapshotTriggeredMsg : Message
    {
        public const string k_RosMessageName = "danger_zone_msgs/SnapshotTriggered";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public string filename;
        //  Name of bag file to save snapshot to.
        //  if it ends in .bag, this exact filename will be saved.
        //  otherwise, the current datetime and .bag will be appended to the name
        //    example: "test" -> test2018-05-23-10-04-20.bag
        //    example: "test.bag" -> test.bag
        public TriggeredTopicDetailsMsg[] topics;
        //  List of topics to include in snapshot.
        //  If empty, all buffered topics will be written
        public BuiltinInterfaces.TimeMsg start_time;
        //  Earliest timestamp for a message to be included in written bag
        //  If time(0), start at the earliest message in each topic's buffer
        public BuiltinInterfaces.TimeMsg stop_time;
        //  Latest timestamp for a message to be included in written bag
        //  If time(0), stop at the most recent message in each topic's buffer

        public SnapshotTriggeredMsg()
        {
            this.header = new Std.HeaderMsg();
            this.filename = "";
            this.topics = new TriggeredTopicDetailsMsg[0];
            this.start_time = new BuiltinInterfaces.TimeMsg();
            this.stop_time = new BuiltinInterfaces.TimeMsg();
        }

        public SnapshotTriggeredMsg(Std.HeaderMsg header, string filename, TriggeredTopicDetailsMsg[] topics, BuiltinInterfaces.TimeMsg start_time, BuiltinInterfaces.TimeMsg stop_time)
        {
            this.header = header;
            this.filename = filename;
            this.topics = topics;
            this.start_time = start_time;
            this.stop_time = stop_time;
        }

        public static SnapshotTriggeredMsg Deserialize(MessageDeserializer deserializer) => new SnapshotTriggeredMsg(deserializer);

        private SnapshotTriggeredMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.filename);
            deserializer.Read(out this.topics, TriggeredTopicDetailsMsg.Deserialize, deserializer.ReadLength());
            this.start_time = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.stop_time = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.filename);
            serializer.WriteLength(this.topics);
            serializer.Write(this.topics);
            serializer.Write(this.start_time);
            serializer.Write(this.stop_time);
        }

        public override string ToString()
        {
            return "SnapshotTriggeredMsg: " +
            "\nheader: " + header.ToString() +
            "\nfilename: " + filename.ToString() +
            "\ntopics: " + System.String.Join(", ", topics.ToList()) +
            "\nstart_time: " + start_time.ToString() +
            "\nstop_time: " + stop_time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
