//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DangerZone
{
    [Serializable]
    public class TriggeredTopicDetailsMsg : Message
    {
        public const string k_RosMessageName = "danger_zone_msgs/TriggeredTopicDetails";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        //  The fully-qualified topic name
        public string type;
        //  The fully-qualified message type

        public TriggeredTopicDetailsMsg()
        {
            this.name = "";
            this.type = "";
        }

        public TriggeredTopicDetailsMsg(string name, string type)
        {
            this.name = name;
            this.type = type;
        }

        public static TriggeredTopicDetailsMsg Deserialize(MessageDeserializer deserializer) => new TriggeredTopicDetailsMsg(deserializer);

        private TriggeredTopicDetailsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "TriggeredTopicDetailsMsg: " +
            "\nname: " + name.ToString() +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
